#!/bin/php
<?php
/**
*
* Project: DBDNS
* Author: John Hart
* Licence: Apache 2.0
* 
*
* DO NOT EDIT THIS FILE
*
*/

// Check and load config file
if( file_exists( "config.php" ) ) {
        require_once 'config.php';
} else {
        die( "Cannot load configuration file!" );
}

// Connect to the database
$db = new PDO( "mysql:host=" . DB_HOST . ":" . DB_PORT . ";dbname=" . DB_NAME , DB_USERNAME , DB_PASSWORD );

// check zone folder exists
if( ! file_exists( ZONE_DIR ) ) {
        mkdir( ZONE_DIR );
}
// Get zones
$getZones = $db->query( "SELECT * FROM `zones`" );
$getRecords = $db->prepare( "SELECT * FROM `records` WHERE `zone_id` =:zone_id" );
while( $zone = $getZones->fetch( PDO::FETCH_ASSOC ) ) {
        $file_location = ZONE_DIR . "/db." . $zone['domain'];
        $serial = $zone['soa_serial'] . rand( 2 , 2 );
        $content = ";\n";
        $content .= "; Generated automatically by DBDNS on " . date( "Y-m-d H:i" ) . "\n";
        $content .= ";\n";
        $content .= "\n";
        $content .= "@     IN     SOA   " . $zone['domain'] .". " . str_replace( "@" , "." , ADMIN_EMAIL ) . ". (" . $serial . " " . $zone['soa_refresh'] . " " . $zone['soa_retry'] . " ">
        // Get records
        $zone_id = $zone['id'];
        $getRecords->execute( [ ':zone_id' => $zone_id ] );
        while( $record = $getRecords->fetch( PDO::FETCH_ASSOC ) ) {
                $content .= "\n";
                $content .= $record['record'] . "    " . $record['ttl'] . "    IN     " . $record['record_type'] . "    " . $record['location'] . "";
        }
        // Does this zone exist

        $handle = fopen( $file_location , "w" );
        fwrite( $handle , $content );
        fclose( $handle );
}
// Generate bind config
$getZones = $db->query( "SELECT `domain`,`zone_type` FROM `zones`" );
$bind_config_file = "";
while( $zone = $getZones->fetch( PDO::FETCH_ASSOC ) ) {
        $bind_config_file .= 'zone "' . $zone['domain'] . '". {\n";
        $bind_config_file .= "    type " . $zone['zone_type'] . ";\n";
        $bind_config_file .= '    file "' . ZONE_DIR . '/db.' . $zone['domain'] . '";\n';
        if( $zone['zone_type'] == "backup" ) {
                $bind_config_file .= '    masters { ' . $zone['master'] . '; };\n';
        }
        $bind .= "};\n"
}
$bind = fopen( CONFIG_FILE , "w" );
fwrite( $bind , $bind_config_file );
fclose( $bind );
?>
